# Generated by Django 3.0.8 on 2020-07-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200730_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemextraimage',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='itemextraimage',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
